name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/spiik.com:latest
      - name: Deploy to DigitalOcean Droplet
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh $DROPLET_USER@$DROPLET_IP << 'ENDSSH'

            # Pull the latest image
            docker pull kodkollektivetkalmar/spiik.com:latest
            echo "Image pulled"
            
            # Stop and remove the existing container (if it exists)
            docker ps -q --filter "name=spiikcom" | grep -q . && docker stop spiikcom
            docker ps -aq --filter "name=spiikcom" | grep -q . && docker rm spiikcom
            echo "Container stopped and removed"
            
            # Run the new container
            docker run -d --name spiikcom -p 8080:3000 kodkollektivetkalmar/spiik.com:latest
            echo "Container started"
          ENDSSH